version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  catalogdb:
    image: mongo
  
  basketdb:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  portainer:
    image: portainer/portainer-ce

  discountdb:
     image: postgres

  pgadmin:
     image: dpage/pgadmin4

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:


