version: '3.4'

services:
  catalog.api:
    container_name: catalogapi
    environment:   
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"   
    ports:
      - "8000:80"
    depends_on: 
      - catalogdb
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379" 
  
  pgadmin:
     container_name: pgadmin
     environment: 
         - PGADMIN_DEFAULT_EMAIL=vanjaneya@beckman.com
         - PGADMIN_DEFAULT_PASSWORD=admin1234
     ports:
         - "5050:80"
     volumes:
         - pgadmin_data:/root/.pgadmin
  
  discountdb:
     container_name: discountdb 
     environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1234
        - POSTGRES_DB=DisccountDb 
     restart: always
     ports:
         - "5432:5432"
     volumes:
         - postgres_data:/var/lib/postgresql/data/

  basket.api:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    ports:
      - "8001:80"
    depends_on: 
      - basketdb
  portainer:
    container_name: portainer
    restart: always
    ports:
        - "8080:8000"
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

