version: '3.4'

services:
  catalog.api:
    container_name: catalogapi
    environment:   
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"   
    ports:
      - "8000:80"
    depends_on: 
      - catalogdb
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
       
